### PR TITLE
Add JSON, RDF, JSON-LD, and JSON Schema as glossary terms

### PR DESCRIPTION
**Pull request by u8sand**
Relevant for https://github.com/nih-cfde/the-fair-cookbook/pull/45

### CODE REVIEW

**Comment by ACharbonneau** [comment]
Thanks! Some of the rendering software seems to be throwing an error, I think it's related to a recent update in the theme. I'll fix the render issue and get this merged in.

**Comment by u8sand** [comment]
@ACharbonneau awesome, thanks. It should be ready hopefully I don't find other terms :+1:

**Comment by marisalim** [comment]
this PR is mergeable now after we fixed a mkdocs update. @u8sand are there anymore terms to add here?

**Comment by u8sand** [comment]
@marisalim No more terms this is good to go; thanks!

**Review by marisalim — APPROVED** [review]
looks great!

**Pull request merged**
