### PR TITLE
Portaldoc -- docx -> markdown

### PR DESCRIPTION
**Pull request by jeremywalter**
file needs to be renamed when approved

### CODE REVIEW

**Comment by ACharbonneau** [comment]
This is a good start, but it needs some work.

- please make it the right filename, there's no reason to do a second PR just to change the name.
- you seem to have tried to keep things like the TOC, and version and whatnot that I said we don't want. They do not make sense in the website: https://cfde-published-documentation--103.com.readthedocs.build/en/103/about/portal/
- the headers should be made into real headers so they render as the TOC on the site

**Comment by ACharbonneau** [comment]
I would hold off a moment on fixing this. Apparently Erin is changing the content a bit, and it's probably easier to re-pandoc and edit than to fix this and then try to merge her changes

**Comment by jeremywalter** [comment]
Starting over with the revised doc -- what can/should I do about all of the images? @ACharbonneau

**Comment by ACharbonneau** [comment]
there should be an image directory in docs

**Comment by jeremywalter** [comment]
so do I need to go find the images and move them there? 

> there should be an image directory in docs
so I need to go find the images and move them here too?

**Comment by ACharbonneau** [comment]
https://drive.google.com/drive/folders/1ob0M0WGCBF4safqzYNJSGvVygwihLawf

**Comment by ACharbonneau** [comment]
it needs a yaml header with the title

**Comment by ACharbonneau** [comment]
and the enormous logo needs to be deleted

**Comment by jeremywalter** [comment]
I think/hope this is done and ready for review

**Review by ACharbonneau — APPROVED** [review]

**Pull request merged**
