### PR TITLE
merging in dev

### PR DESCRIPTION
**Pull request by ACharbonneau**
I might just get rid of dev. I'm genuinely not sure how to make it work with the evergrowing octopus of submodules

### CODE REVIEW

**Comment by ACharbonneau** [comment]
@s-canchi Can you figure out why this is making the preview site render weird and fix it? I assume it has something to do with the versions you mentioned being a problem for training.

**Comment by s-canchi** [comment]
Will take a look later today. Till we figure it out, would be best to use the previous working version (mkdocs-material v6.2.6).

**Comment by ACharbonneau** [comment]
@nih-cfde/training Any chance someone could look at this today? I need to add in a new submodule and have the new site up next week, and I can't start until I have the latest in stable

**Comment by marisalim** [comment]
Sure, i can help if needed @s-canchi

**Comment by s-canchi** [comment]
Will be done today!

**Review by marisalim — APPROVED** [review]
lgtm!

**Comment by ACharbonneau** [comment]
Thank you!

**Pull request merged**
