### PR TITLE
add matamo analytics

### PR DESCRIPTION
**Pull request by s-canchi**
Added matamo analytics code. 

Merge into `stable` is required to get tracking setup on the published documentation website which is anticipated to have increased traffic after portal release.

### CODE REVIEW

**Comment by s-canchi** [comment]
This line of code needs to be updated to the published document domain : `_paq.push(["setCookieDomain", "*.training.nih-cfde.org"]);`

**Comment by s-canchi** [comment]
current docs site: https://docs.nih-cfde.org/en/latest/

**Review by ctb — CHANGES_REQUESTED** [review]
I think `docs/images/datapackageflow.png` should be removed, yes?

**Comment by ctb** [comment]
hi @s-canchi @jeremywalter see review. also, please update branch to latest, and include a brief statement+justification at the top for doing a merge into `stable` - thanks!

**Comment by s-canchi** [comment]
> I think docs/images/datapackageflow.png should be removed, yes?

This flow diagram is used in the wiki home page: https://github.com/nih-cfde/published-documentation/wiki
So I don't think it should be removed but maybe @ACharbonneau can comment on it. Updated justification in the description above.

**Comment by ctb** [comment]
> > I think docs/images/datapackageflow.png should be removed, yes?
> 
> This flow diagram is used in the wiki home page: https://github.com/nih-cfde/published-documentation/wiki
> So I don't think it should be removed but maybe @ACharbonneau can comment on it.

OK - the title of this PR is "add matomo analytics" - is the flow diagram used for that? if not, it belongs in a separate PR, _or_ the PR title description should be updated to encompass it, I think.

**Comment by s-canchi** [comment]
I kept running into git conflict for binary files and it came from the flowdiagram.png file. To resolve it I added it back to this PR using these steps : https://stackoverflow.com/questions/278081/resolving-a-git-conflict-with-binary-files

Not sure if that was the optimal solution.

**Comment by ctb** [comment]
hmm, but I don't see `datapackageflow.png` in the stable branch, so not sure where a conflict would be coming from.

do you intend to add it in this PR, or what? confused :)

**Comment by marisalim** [comment]
hm, it is here https://github.com/nih-cfde/published-documentation/blob/stable/docs/images/datapackageflow.png - this is an image used for the published docs wiki page

**Comment by ctb** [comment]
> hm, it is here https://github.com/nih-cfde/published-documentation/blob/stable/docs/images/datapackageflow.png - this is an image used for the published docs wiki page

ok, thanks. dunno why my find file search didn't find it 🤷 

so in that case we _really_ don't want it in this PR... let me see if I can remove it.

**Comment by ctb** [comment]
OK, did the following:

```
git checkout scanchi-add-analytics
git diff --stat stable
```
this showed that the file was massively increased in size...
>custom/partials/header.html     |  17 +++++++++++++++++
>docs/images/datapackageflow.png | Bin 32897 -> 413484 bytes

so I then explicitly grabbed the version from the `stable` branch using git show:
```
git show stable:docs/images/datapackageflow.png > docs/images/datapackagg
git diff --stat stable
```
and life is now good:
> custom/partials/header.html | 17 +++++++++++++++++
>1 file changed, 17 insertions(+)

and commit:
```
git commit -am "Replace datapackageflow with version from stable"
git push
```
I'll go ahead and merge this.

**Pull request merged**
