### PR TITLE
add user guide to tabs

### PR DESCRIPTION
**Pull request by raynamharris**
add user guide to the tabs and  alphabetize

### CODE REVIEW

**Comment by raynamharris** [comment]
https://cfde-published-documentation--375.com.readthedocs.build/en/375/

**Comment by raynamharris** [comment]
preview
Screen Shot 2022-05-02 at 11 06 37 AM

**Comment by raynamharris** [comment]
Screen Shot 2022-05-02 at 11 09 15 AM

**Review by jessicalumian — APPROVED** [review]
looks good! I like the side bar on thin screens :)

**Pull request merged**
