### PR TITLE
Updated Guide with new Data Review changes

### PR DESCRIPTION
**Pull request by fridayek**
@nih-cfde/training @ACharbonneau I added the new Data Review sections and made a few changes to existing sections as well. I was unable to replace outdated screenshots or add new ones, though. Can someone help me with that? 

FYI - the source file of the CFDE User Guide (along with all updated screenshots) is located in a Google Doc here:  https://docs.google.com/document/d/1S5ll51sKuFuV3uzCQrCZM_y23nqevP55x42guhAsuOI/edit#heading=h.qps39qfktve9

### CODE REVIEW

**Comment by s-canchi** [comment]
Hi @fridayek , Happy to help with this PR later today.

**Comment by s-canchi** [comment]
I have made all the changes in my local repo but I am running into 403 forbidden type error when I push those changes. I will look into resolving it tomorrow.

**Review by fridayek — COMMENTED** [review]
Thank you for your help with the images, @s-canchi!

**Review by s-canchi — APPROVED** [review]
lgtm!

**Comment by s-canchi** [comment]
@fridayek - Go ahead and merge the PR if everything looks good. These changes are already approved :)

**Pull request merged**
