### PR TITLE
New TOC and adding specifications-and-documentation submodule

### PR DESCRIPTION
**Pull request by ACharbonneau**
Would update the cookbook to use `.pages` files in each folder to automatically build a table of contents for display in the documentation site. It required some rearrangement of the folders under `content`

A preview of the site is here: https://cfde-published-documentation.readthedocs-hosted.com/en/preview/

CAN ONLY BE MERGED IN TANDEM WITH https://github.com/nih-cfde/the-fair-cookbook/pull/38

### CODE REVIEW

**Comment by marisalim** [comment]
the mkdocs awesome-pages plugin is soon changing the syntax from `arrange:` (will be deprecated) to `nav:`, so whenever the .pages files are added, please use the updated syntax!

**Comment by ACharbonneau** [comment]
This breaks the fair repo. Going to try a different method

**Comment by ACharbonneau** [comment]
OK. Making this work with 1 private submodule and 1 public submodule has been so bad that it distracted me from the election all day. 

For @nih-cfde/brown this link should render: https://cfde-published-documentation--68.com.readthedocs.build/en/68/

It would be great if someone on my team could review this today or tomorrow at the latest. I had to merge in the FAIR changes to make these merge, but that made the website broken for most of their files until this is merged. Dependencies are awful. 

The auto-update of @abradyIGS stuff might not work quite right yet. I made the bot have the permissions I think it needs, but I'll have to fiddle with it once he's actually trying it.

**Comment by marisalim** [comment]
looking at this link: https://cfde-published-documentation--68.com.readthedocs.build/en/68/

- can you re-arrange the TOC so that 'Overview' is at the top? also, the links on the Overview page are broken.
image

there are many broken links - @ACharbonneau do they need to be fixed in this PR or will some/many of them be fixed after this is merged? the fair cook book docs do render in this version :)

here are a few obvious broken links i noticed from clicking around: 
- link to "CFDE website" in the TOC https://cfde-published-documentation--68.com.readthedocs.build/en/68/about/LICENSE/ - i get a security warning message to the link
- the link to the license is broken on this page: https://cfde-published-documentation--68.com.readthedocs.build/en/68/specifications-and-documentation/CONTRIBUTING/
- looks like the docs are there, just need to edit link paths on this landing page - https://cfde-published-documentation--68.com.readthedocs.build/en/68/the-fair-cookbook/content/intro/
- i think it's already been noted somewhere, maybe the-fair-cookbook? but since i found it, this image is broken https://cfde-published-documentation--68.com.readthedocs.build/en/68/the-fair-cookbook/content/recipes/Compliance/fairshake/#reviewing-the-state-of-fairness-in-a-project

**Comment by ACharbonneau** [comment]
License link: that is my problem

CFDE website warning: That's a DNS thing that I have no control over
All the other things: are coming from the FAIR cookbook, you/they/someone would need to make a PR there to fix it

**Comment by ctb** [comment]
There seems to be more going on here than is in the PR description, which makes reviewing this a challenge.

I'll rubber stamp this, but here are some questions that you could answer that would make me feel better about it --

* what's with all the docs/spec-and-docs/ file removal? 
* how does the much-reduced mkdocs.yml file work?
* could you please provide some text with a conceptual description of what is going on with the submodules?

thanks!

**Review by ctb — APPROVED** [review]
I have a vague idea of what's going on. Seems OK.

**Comment by ACharbonneau** [comment]
> There seems to be more going on here than is in the PR description, which makes reviewing this a challenge.
> 
> I'll rubber stamp this, but here are some questions that you could answer that would make me feel better about it --
> 
> * what's with all the docs/spec-and-docs/ file removal?

The deletions are because we had been manually porting over the docs from the specifications-and-documentation repo to here for rendering. So when I added that repo as a proper sub-module, I had to delete the local, manual copy. 

> * how does the much-reduced mkdocs.yml file work?
I've just added instructions to the README page here. I was adding them to the respective sub-modules since the work happens there, but now it's here too. I can add more detail if needed. We're using a plugin called awesome pages. It dynamically builds the nav info for the mkdocs.yml from `.pages` files in each directory. With a central mkdocs.yml, there is a problem where adding pages in a submodule means you need to make matched PRs across this repo and the submodule repo, and neither works until both are merged. By moving to this method, the nav can be controlled with a single PR in the originating repo in all cases.

> * could you please provide some text with a conceptual description of what is going on with the submodules?

This is also in the new README text, but this repo acts as a scaffold for building the basic website. The only 'content' it has are the About pages. All of the other content is pulled from master branches of the-fair-cookbook and specifications-and-documentation repos. This makes it so that I can maintain a single documentation website, but allow the documentation owners to maintain control of their own information, and to work according to their own workflows. For instance, one feature of The FAIR Cookbook is that it is a standalone, instantiable collection of ipython notebooks that a user can install locally and launch dockers from and all sorts of neat stuff. This set up allows us to have The FAIR Cookbook repo maintain all of the machinery necessary for that to work, but to still be included in the main CFDE documentation site. 

> 
> thanks!

**Pull request merged**
