### PR TITLE
update mkdocs tab syntax, updating C2M2 docs

### PR DESCRIPTION
**Pull request by marisalim**
Addressing [updates to Mkdocs syntax](https://squidfunk.github.io/mkdocs-material/upgrading/#changes-to-mkdocsyml) with latest version; this fixes rendering issues for the navigation bar on the website

Change syntax under "features" in the mkdocs.yml file to:
```
features:
    - navigation.tabs
    - navigation.instant
```

Updating C2M2 docs with latest version. 

preview: https://cfde-published-documentation--83.com.readthedocs.build/en/83/

### CODE REVIEW

**Comment by marisalim** [comment]
this error is currently causing the build-and-deploy action to fail:
```
ERROR   -  Error reading page 'the-fair-cookbook/content/1/testnb/0-rose-metabolites-Python-data-handling.ipynb': No such kernel named venv372 
```

this ipynb file is not currently specified to be rendered on the website. page nav is currently specified in the mkdocs.yml file.

perhaps this error will be fixed when .pages are added (#68)? for now, i'll leave this PR as a draft as it seems other updates to file navigation/specification are needed before the mkdocs navigation bar syntax change can be added.

**Comment by ACharbonneau** [comment]
Don't actually merge this yet, I'm still working on it. but at least it renders now

**Comment by marisalim** [comment]
question on C2M2 doc update:
- [ ] in the Level 1 documentation, there's a link to these [tsv files](https://github.com/nih-cfde/specifications-and-documentation/tree/master/draft-C2M2_example_submission_data/swap_in_as_canonical_after_2020.10.31/HMP__sample_C2M2_Level_1_bdbag.contents), but on the website, the link to this folder doesn't do anything because no file is specified. Github permission is required to open the folder where all the tsv files are. Not sure how we want the files to be made available. The BDBag archive for the files can be downloaded.
> an example Level-1-compliant TSV submission collection can be found here (as a bare collection of TSV files)

**Comment by ACharbonneau** [comment]
> @ACharbonneau - question on C2M2 doc update:
> 
> * [ ]  in the Level 1 documentation, there's a link to these [tsv files](https://github.com/nih-cfde/specifications-and-documentation/tree/master/draft-C2M2_example_submission_data/swap_in_as_canonical_after_2020.10.31/HMP__sample_C2M2_Level_1_bdbag.contents), but on the website, the link to this folder doesn't do anything because no file is specified. Github permission is required to open the folder where all the tsv files are. Not sure how we want the files to be made available. The BDBag archive with these files does download.
> 
> > an example Level-1-compliant TSV submission collection can be found here (as a bare collection of TSV files)

Is there a reason to not just put the files in the website repo?

And if there is, can you make a copy of them in osf and link them?

**Comment by ACharbonneau** [comment]
see https://github.com/dib-lab/cfde/issues/100

**Review by ACharbonneau — APPROVED** [review]
Yay!!

feel free to merge once the osf links get dropped in, this looks great :)

**Pull request merged**
